### ISSUE TITLE
Feedback on YT Video

### ISSUE THREAD

**Issue by DEberhardt** [JustinGrote/PWSH24Examples#1]
Hello,

thank you very much for this wonderful Video and the repository collecting all the information you provide. I could have used this a year ago when I started out on my journey with VSCode and PowerShell ^^
I learned a lot about Visual Studio Code and what I can do with PowerShell! Still a lot to go on (like Github Actions, but I do take it one step after the other :)

People not living on Github (myself included, though soon I can get the permanent resident badge :)) (and the YT Community as a whole) would like to have some links to this repository in the Description of the video.
Links to other elements, like [Cascadia Code](https://github.com/microsoft/cascadia-code) (which is wonderful!) would be nice to have there... Can one write an extension to integrate Fonts into VSCode? I smell an opportunity :D

You cover some settings that my User Settings flagged as "unknown" (because I haven't had the Extension installed), and (I checked) it is currently not part of your Extension Pack: Github Actions

Cheers,
David

**Comment by JustinGrote** [comment]
Thanks for the feedback David! I plan to do an updated video/article as well as using chezmoi to get everything "set up". I appreciate it and will incorporate this info into my next attempt.
